- Ficher source : tco-metro-topologie-pointsarret-td.csv
- Fichier de sorti : stg_star_metro_arrets.csv
- Date de création : 14 Novembre 2025
- Dernière modification : 17 Novembre 2025

- Version(s) : 
    - 1 - 14/11/2025 : Nettoyage du fichier et création du csv "star_metro_arrets"
    - 2 - 17/11/2025 : Renommage du fichier et création du csv "stg_star_metro_arrets"

In [1]:
#Librairie(s) utilisée(s)
import pandas as pd

In [2]:
#Création du dataframe à partir du fichier csv
metro_arrets = pd.read_csv(r"C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\00_Certif\bloc_6\01_data\01_data_bronze\tco-metro-topologie-pointsarret-td.csv", 
                           delimiter=";")
metro_arrets.head()

,Identifiant,Code,Nom,Adresse (numéro),Adresse (voie),Commune (code INSEE),Commune (nom),Coordonnées,Station parente (ID),Station parente (nom),Accessible aux PMR,Stopid du quai gtfs/gtfs-rt,Stopid de la station gtfs/gtfs-rt
0,5071,5071,Saint-Germain,3,place Saint-Germain,35238,Rennes,"48.1107103741532, -1.67642924804993",15058,Saint-Germain,True,6-5071,6-15058
1,5073,5073,Jules Ferry,1,rue de la Croix Carrée,35238,Rennes,"48.1186562170431, -1.67060937032544",15056,Jules Ferry,True,6-5073,6-15056
2,5078,5078,Atalante,1,avenue de Belle Fontaine,35051,Cesson-Sévigné,"48.1271531528695, -1.62785888139907",15051,Atalante,True,6-5078,6-15051
3,5052,5052,Beaulieu - Université,39,avenue Professeur Charles Foulon,35238,Rennes,"48.1220681784334, -1.639408849558",15052,Beaulieu - Université,True,6-5052,6-15052
4,5054,5054,Les Gayeulles,9,rue Guy Ropartz,35238,Rennes,"48.1294068896457, -1.6578679665894",15054,Les Gayeulles,True,6-5054,6-15054


In [3]:
# Nombre de lignes et de colonnes
metro_arrets.shape

(59, 13)

In [4]:
# Nombre de lignes avec valeur
metro_arrets.count()

Identifiant                          59
Code                                 59
Nom                                  59
Adresse (numéro)                     57
Adresse (voie)                       59
Commune (code INSEE)                 59
Commune (nom)                        59
Coordonnées                          59
Station parente (ID)                 59
Station parente (nom)                59
Accessible aux PMR                   59
Stopid du quai gtfs/gtfs-rt          59
Stopid de la station gtfs/gtfs-rt    59
dtype: int64

In [5]:
# Valeurs manquantes
metro_arrets.isnull().sum()

Identifiant                          0
Code                                 0
Nom                                  0
Adresse (numéro)                     2
Adresse (voie)                       0
Commune (code INSEE)                 0
Commune (nom)                        0
Coordonnées                          0
Station parente (ID)                 0
Station parente (nom)                0
Accessible aux PMR                   0
Stopid du quai gtfs/gtfs-rt          0
Stopid de la station gtfs/gtfs-rt    0
dtype: int64

In [6]:
metro_arrets.columns

Index(['Identifiant', 'Code', 'Nom', 'Adresse (numéro)', 'Adresse (voie)',
       'Commune (code INSEE)', 'Commune (nom)', 'Coordonnées',
       'Station parente (ID)', 'Station parente (nom)', 'Accessible aux PMR',
       'Stopid du quai gtfs/gtfs-rt', 'Stopid de la station gtfs/gtfs-rt'],
      dtype='object')

In [7]:
#Création de la colonne 'MVP' pour cibler les communes de la périphérie de Rennes et filtrer le dataset dessus
MVP = [35032,35058,35196,35065,35275,35144,35266,35315,35278,35245,35208,35353,35120,35210,35352,35059,35250,35079,35363,35051,35055,35076,35189,35066,35204,35022,35351,35088,35080,35131,35001,35206,35081,35139,35334,35216,35024,35240,35039,35047,35281,35180]
metro_arrets['MVP'] = metro_arrets['Commune (code INSEE)'].apply(lambda x: 'oui' if x in MVP else 'non')
metro_arrets['MVP'].describe()

count      59
unique      2
top       non
freq       51
Name: MVP, dtype: object

In [8]:
#Création du mask pour filtrer le dataset sur les communes sélectionnées dans la périphérie de Rennes
mask = (metro_arrets['MVP'] == 'oui')
metro_arrets = metro_arrets[mask]

metro_arrets.shape

(8, 14)

In [9]:
# Split de la colonne coordonnées en latitude et longitude
metro_arrets[['latitude', 'longitude']] = metro_arrets['Coordonnées'].str.split(',', expand=True)
metro_arrets.head()

,Identifiant,Code,Nom,Adresse (numéro),Adresse (voie),Commune (code INSEE),Commune (nom),Coordonnées,Station parente (ID),Station parente (nom),Accessible aux PMR,Stopid du quai gtfs/gtfs-rt,Stopid de la station gtfs/gtfs-rt,MVP,latitude,longitude
2,5078,5078,Atalante,1,avenue de Belle Fontaine,35051,Cesson-Sévigné,"48.1271531528695, -1.62785888139907",15051,Atalante,True,6-5078,6-15051,oui,48.1271531528695,-1.62785888139907
11,5065,5065,Saint-Jacques - Gaîté,1 B,rue Louis Braille,35281,Saint-Jacques-de-la-Lande,"48.0922543436006, -1.70335007013448",15064,Saint-Jacques - Gaîté,True,6-5065,6-15064,oui,48.0922543436006,-1.70335007013448
14,5050,5050,Cesson - Viasilva,14,la Rochelle,35051,Cesson-Sévigné,"48.1314259119796, -1.62024738680177",15050,Cesson - Viasilva,True,6-5050,6-15050,oui,48.1314259119796,-1.62024738680177
15,5051,5051,Atalante,1,avenue de Belle Fontaine,35051,Cesson-Sévigné,"48.1271194329088, -1.62826328652191",15051,Atalante,True,6-5051,6-15051,oui,48.1271194329088,-1.62826328652191
20,5063,5063,La Courrouze,NaN,rue Lucie et Raymond Aubrac,35281,Saint-Jacques-de-la-Lande,"48.0963105845976, -1.69831046826014",15063,La Courrouze,True,6-5063,6-15063,oui,48.0963105845976,-1.69831046826014


In [10]:
# Selection des colonnes utiles
keep_cols = ['Identifiant','Nom', 'Commune (code INSEE)', 'latitude', 'longitude']
df = metro_arrets.loc[:,keep_cols]
df.head()

,Identifiant,Nom,Commune (code INSEE),latitude,longitude
2,5078,Atalante,35051,48.1271531528695,-1.62785888139907
11,5065,Saint-Jacques - Gaîté,35281,48.0922543436006,-1.70335007013448
14,5050,Cesson - Viasilva,35051,48.1314259119796,-1.62024738680177
15,5051,Atalante,35051,48.1271194329088,-1.62826328652191
20,5063,La Courrouze,35281,48.0963105845976,-1.69831046826014


In [11]:
# Renommage des colonnes gardées
cols_new = ["id_arret", "nom_arret", "code_geo","latitude", "longitude"]
df.columns = cols_new
df.head()

,id_arret,nom_arret,code_geo,latitude,longitude
2,5078,Atalante,35051,48.1271531528695,-1.62785888139907
11,5065,Saint-Jacques - Gaîté,35281,48.0922543436006,-1.70335007013448
14,5050,Cesson - Viasilva,35051,48.1314259119796,-1.62024738680177
15,5051,Atalante,35051,48.1271194329088,-1.62826328652191
20,5063,La Courrouze,35281,48.0963105845976,-1.69831046826014


In [12]:
# Vérification des types des colonnes
df.dtypes


id_arret      int64
nom_arret    object
code_geo      int64
latitude     object
longitude    object
dtype: object

In [13]:
df.columns

Index(['id_arret', 'nom_arret', 'code_geo', 'latitude', 'longitude'], dtype='object')

In [14]:
# Changement de types pour certaines colonnes (bien penser à remettre df =): 
df = df.astype({
    'nom_arret': 'string',
    'latitude' : 'float64',
    'longitude' : 'float64'
})
df.dtypes

id_arret              int64
nom_arret    string[python]
code_geo              int64
latitude            float64
longitude           float64
dtype: object

In [15]:
# Visualisation du dataframe
df.sort_values(by='id_arret')

,id_arret,nom_arret,code_geo,latitude,longitude
14,5050,Cesson - Viasilva,35051,48.131426,-1.620247
15,5051,Atalante,35051,48.127119,-1.628263
20,5063,La Courrouze,35281,48.096311,-1.698310
28,5064,Saint-Jacques - Gaîté,35281,48.091839,-1.703875
11,5065,Saint-Jacques - Gaîté,35281,48.092254,-1.703350
36,5066,La Courrouze,35281,48.096730,-1.698552
2,5078,Atalante,35051,48.127153,-1.627859
31,5079,Cesson - Viasilva,35051,48.131549,-1.619862


In [16]:
# Nombre de communes desservies par le métro en périphérie de Rennes
df['code_geo'].unique()

array([35051, 35281], dtype=int64)

Métro de la ligne b : seulement 2 villes desservies : Cesson-Sévigné (35051) and Saint-Jacques-de-la-Lande (35281)

In [17]:
print(f'Différent arrêts: {df['id_arret'].unique()}')

Différent arrêts: [5078 5065 5050 5051 5063 5064 5079 5066]


On a bien 4 arrêts de métro b qui desservent les deux communes de la périphérie de Rennes, mais 8 arrêts : 2 par station

In [ ]:
# Export as a csv table
df.to_csv('stg_star_metro_arrets.csv', sep=';', index=False)